# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woVkMetKWq9qsNJwohbDWqWfEEezw0Mo
"""

!pip install Jupyter-Dash

import plotly.express as px
from jupyter_dash import JupyterDash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import dash_table
import plotly.graph_objects as go
import pandas as pd 
import numpy as np

app = JupyterDash(__name__)

"""#Load random data from the built-in Plotly Database"""

df = px.data.gapminder()
df

"""Create a sunburst graph fig"""

fig = px.sunburst(df,path=['continent','country','year'],
                  values = 'pop',
                  color = 'lifeExp',
                  hover_data=['iso_alpha'],
                  color_continuous_scale='twilight',
                  color_continuous_midpoint=np.average(df['lifeExp'],weights = df['pop']))
fig

"""Build a dash data table

We are creating a dashtable by changing the dataframe in dictionary
"""

table = dash_table.DataTable(df.to_dict('records'),[{"name":i,"id":i} for i in df.columns])

"""Add html components and fiure to app"""

app.layout =html.Div(
    [
        html.H1('SHOWCASE DASHBOARD',style ={'color': 'grey'}), 
     dcc.Graph(figure=fig),
     html.Br(),
     table
    ]
)

"""Run app inline

```
# This is formatted as code
```Inline will outpt the dashbaord in colab,"external" will output it in your browser via locahost


"""

app.run_server(mode ='inline')