# -*- coding: utf-8 -*-
"""Pyspark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwRhHUBntAWoiCzL16AOG1aDfwHHNmB5
"""

!pip install pyspark

"""Importing the packages"""

from pyspark.sql import SparkSession
from pyspark.sql.types import StringType, StructType, StructField, IntegerType
import pyspark.sql.functions as func

"""Creating the SparkSession"""

spark = SparkSession.builder.appName("FirstApp").getOrCreate()

"""Defining Schema for your Dataframe """

myschema =  StructType([\
                        StructField("userID", IntegerType(), True),
                        StructField("name", StringType(), True),
                        StructField("age", IntegerType(), True),
                        StructField("friends", IntegerType(), True),
                        ])

myschema

"""Creating Dataframe on a CSV file"""

people = spark.read.format("csv")\
    .schema(myschema)\
    .option("path","/content/fakeFriends.csv")\
    .load()

print(people)

"""Performing all Transformations"""

output = people.select(people.userID, people.name\
                       ,people.age, people.friends)\
                       .where(people.age<30).withColumn('insert_ts',func.current_timestamp())\
                       .orderBy(people.userID)

output.count()

"""Creating a Temp View"""

output.createOrReplaceTempView("people")

spark.sql("select name, age,friends, insert_ts from people").show()